cytaty = [
	"Nie wiesz, co to prawdziwa strata. Można jej doświadczyć tylko wtedy, kiedy kochasz coś bardziej, niż siebie samego",
	"Trudno być złym, kiedy świat ma do zaoferowania tyle piękna",
	"Niektórzy mają tragedię we krwi",
	"Każdy umiera, ale nie każdy tak naprawdę żyje",
	"W tej sekundzie, przysięgam, jesteśmy jednym z nieskończonością",
	"Mówią, że kiedy spotykasz miłość swojego życia, czas się zatrzymuje. To prawda",
	"Szczeście można znaleźć nawet w najciemniejszych chwilach, jeśli tylko nosi się w sobie światło",
	"Śmiech potrafi być potężny. Czasem to jedyna broń, którą dysponujemy",
	"Kwiat, który kwitnie mimo przeciwności losu, to najrzadszy i najpiękniejszy z nich wszystkich",
	"Nawet mrok kiedyś przeminie. Wkrótce nadejdzie nowy dzień, a kiedy wzejdzie słońce, rozbłyśnie jaśniej, niż kiedykolwiek wcześniej",
	"Przeszłość to tylko bajka, którą sobie opowiadamy",
	"Jesteś tym, co kochasz, a nie tym, co inni kochają w Tobie",
	"Niektórych ptaków nie powinno się trzymać w klatce. Są na to zbyt piękne",
	"Nigdy nie bój się marzyć o czymś lepszym, słonko",
	"Stań się tym, kim marzysz, żeby być",
	"Niektóre nieskończoności są większe od innych nieskończoności",
	"Kiedy spadająca gwiazda rozcina mrok i zamienia noc w dzień, pomyśl życzenie... i pomyśl o mnie. Uczyń swoje życie spektakularnym. Ja tak zrobiłem",
	"Pamiętamy bohaterów, ale to legendy nigdy nie umierają. Idź za głosem serca, a nie popełnisz błędu",
	"Wiem, że szansa na sukces jest mała, ale czy to ważne? Odpowiedzi znajdujemy tylko wtedy, kiedy nie przestajemy próbować",
	"Odważni może żyją krótko, ale ostrożni nie żyją w ogóle",
	"Po raz pierwszy pozwólmy sobie być tymi, kim jesteśmy, kimkolwiek jesteśmy",
	"Życie mija szybko. Jeśli czasem się nie zatrzymasz, żeby się nim ponapawać, łatwo je przegapić",
	"Czasem kochamy kogoś tak bardzo, że musimy się powstrzymywać. Gdybyśmy znali siłę ich miłości, zabiłaby nas",
	"Ta właściwa osoba będzie widziała dobro we wszystkim, co robisz, niezależnie od tego jaki jesteś",
	"Dlaczego upadamy, Bruce? Po to, żeby nauczyć się, jak wstawać",
	"Kiedyś patrzyliśmy w niebo i zastanawialiśmy się, jakie jest nasze miejsce w kosmosie. Teraz patrzymy pod nogi i gdybamy, czy jest dla nas miejsce wśród piachu",
	"To szansy definiują nasze życia. Nawet te, które przegapiliśmy",
	"Każda chwila jest dobra, żeby zmienić swoje życie", "Najlepszy sposób na osiągnięcie sukcesu, to postępować według rad, które dajemy innym. - Harold Taylor", "Najlepszy sposób na osiągnięcie sukcesu, to postępować według reguł, które dajemy innym. - Harold Taylor", "Aby więcej zarabiać, musisz się więcej nauczyć. - Brian Tracy", "Standardowa edukacja zapewni Ci przeżycie. Samokształcenie - fortunę. Jim Rohn", "Przyszłość należy do tych, którzy przygotowują się na nią dzisiaj. - Malcolm X", "Przeciwności, z którymi musimy się zmierzyć, często sprawiają, że stajemy się silniejsi. To, co dziś wydaje się stratą, jutro może okazać się zyskiem. -Nick Vujicic", "Nic nie jest podawane na tacy - każdy zawsze trafia na jakieś przeszkody po drodze. Kiedy się pojawiają, zastanów się jak je pokonać, a nie myśl o tym, że to już koniec drogi. - Michael Jordan", "Twój czas jest ograniczony, więc nie marnuj go na bycie kimś, kim nie jesteś. - Steve Jobs", "Jeśli to, co robisz, nie przybliża Cię do Twojego celu, to Cię od niego oddala. - Brian Tracy", "Szaleństwo to robienie ciągle tych samych rzeczy w oczekiwaniu różnych rezultatów. - Albert Einstein", "Najważniejszym powodem, dla którego ludzie nie osiągają tego, czego chcą, jest to, że sami nie wiedzą, czego chcą. - Harv Eker", "Porażka nie czyni Cię przegranym. Czyni za to poddawanie się, godzenie się z nią i odmowa ponownego próbowania. - Richard Exely ", "Gdy wszyscy wiedzą, że coś jest niemożliwe, przychodzi ktoś, kto o tym nie wie i robi to! - Napoleon Hill ", "Nie czekaj, pora nigdy nie będzie idealna. -Napoleon Hill ", "Istnieją tylko dwa dni w roku, w których nic nie może być zrobione. Jeden nazywamy wczoraj, a drugi jutro. - Dalai Lama", "Wielkie umysły mają cele, inni mają życzenia. - Washington Irving", "Przyszłość zaczyna się dzisiaj, nie jutro. - Jan Paweł II ", "Zacznij tam, gdzie jesteś. Użyj tego, co masz. Zrób, co możesz! - Artur Ashe", "Śmiałe marzenia mogą się przekształcić w rzeczywistość! - Napoleon Hill ", "Jesteśmy tym, co w swoim życiu powtarzamy. Doskonałość nie jest jednorazowym aktem, lecz nawykiem. - Arystoteles ", "Nie odktywa się nowych lądów bez zgody na to, że na długi czas straci się z oczu brzeg. - Andre Gide", "Nie ma nic złego w świętowaniu sukcesu, ale ważniejsze jest wyciągnięcie nauki z porażki. - Bill Gates", "Dwa najważniejsze dni Twojego życia to ten, w którym się urodziłeś oraz ten, w którym dowiedziałeś się po co. - Mark Twain ", "Żyje się tylko raz, ale jeśli żyjesz dobrze, ten raz wystarczy. - Mae West", "Co należy zrobić po upadku? To co robią dzieci: podnieść się. - Aldous Huxley", "Choć nikt nie może cofnąć się w czasie i zmienić początku na zupełnie inny, to każdy może zacząć dziś i stworzyć całkiem nowe zakońćzenie. - Carl Bard"
]
